// This file is automatically generated by the system and contains the Stripe configuration for the project
// Note: In production environments, please use environment variables to store this sensitive information


const config = {
	metadata: {
		title: "Saas Starter",
		description: "Saas Starter Kit for demo purpose ",
		keywords: ["Saas", "Starter Kit", "Demo", "Note Taking", "AI", "Chatbot"],
	},
	theme: {
		colors: {
			primary: '#5059FE',
			primaryHover: '#4048ed',
			border: '#E5E7EB',  // Standard border color
			borderHover: '#D1D5DB'  // Border hover color
		}
	},
	// Stripe plan configuration
	// IMPORTANT: Update the priceId and productId values with your actual Stripe Price IDs
	// Get them from: https://dashboard.stripe.com/test/products (for test mode)
	// or https://dashboard.stripe.com/products (for live mode)
	stripe: {
		free: {
			monthPrice: 0,
			yearPrice: 0,
			monthPriceId: '',
			yearPriceId: '',
			productId: '',
			name: 'Free',
			description: 'Free plan',
		},
		basic: {
			monthPrice: 15.80,
			yearPrice: 160.50,
			// TODO: Get the actual Price IDs from Stripe Dashboard
			// Click on the "..." menu next to each price in Stripe to copy the Price ID
			monthPriceId: 'price_1SVi9cJAVAt7OcdAgXIYR9OP', // ← Replace with your Basic monthly price ID (15.80 $US/month)
			yearPriceId: 'price_1SViA1JAVAt7OcdA4QHx5dWg', // ← Replace with your Basic yearly price ID (160.50 $US/year)
			productId: 'prod_TSdQV1eOt10tFF', // ← Replace with your Basic product ID
			name: 'Basic',
			description: 'Basic plan',
		},
		pro: {
			monthPrice: 20.00,
			yearPrice: 180.00,
			// TODO: Get the actual Price IDs from Stripe Dashboard
			// Click on the "..." menu next to each price in Stripe to copy the Price ID
			monthPriceId: 'price_1SViASJAVAt7OcdAyMkq0I46', // ← Replace with your Pro monthly price ID (20.00 $US/month)
			yearPriceId: 'price_1SViAkJAVAt7OcdAkBNXvcJ4', // ← Replace with your Pro yearly price ID (180.00 $US/year)
			productId: 'prod_TSdRJfaBhsdn70', // ← Replace with your Pro product ID
			name: 'Pro',
			description: 'Pro plan',
		},
	},
	appName: "saas starter kit",
	socialLinks: {
		github: "https://github.com",
		twitter: "https://twitter.com",
		linkedin: "https://linkedin.com"
	},
	emailProvider: "nodemailer",
};


export default config
